global_costmap:
   global_frame: map
   robot_base_frame: base_link
   update_frequency: 2.0
   publish_frequency: 2.0
   static_map: false
   rolling_window: true
   width: 40
   height: 40
   resolution: 0.2
   publish_voxel_map: true
   transform_tolerance: 0.6